name: CI for Backend

on:
  push:
    branch:
      - "main":
    paths-ignore:
      - REAME.md
      - helm-chart/*
      - Jenkins-server-TF
      - Kubernetes-Manifests-file
    

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      #The will get from the github
      - name: Checkout the code  
        uses: action/checkout@3

      #The ubuntu will install the java
      - name: Setup java          
        uses: action/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "17"

      #The ubuntu will install the nodejs
      - name: set up nodejs       
        uses: action/setup-nodejs@v3
        with:
          node-version: "14"
  
  #sonarqube will setup and run the code quality check
  sonarqube-qulity-check:                   
      - name: setup sonarqube
        uses: SonarSource/sonarqube-scan-action@v1.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
        run: |
          cd Application-Code/backend
          sonar-scanner -Dsonar.projectName=three-tier-backend -Dsonar.projectKey=three-tier-backend

    # Wait for Quality Gate to pass before continuing
      - name: Wait for Quality Gate
        run: |
          curl -u ${{ secrets.SONARQUBE_TOKEN }} "https://sonar.example.com/api/qualitygates/project_status?projectKey=three-tier-backend" \
          | jq '.projectStatus.status' | grep -q 'OK'

    # Run OWASP Dependency-Check Scan
      - name: Run OWASP Dependency-Check Scan
        run: |
          cd Application-Code/backend
          dependency-check --scan ./ --disableYarnAudit --disableNodeAudit -o ./dependency-check-report.xml

    # Publish OWASP Dependency-Check Report
      - name: Publish OWASP Dependency-Check Report
        uses: snyk/actions@v1
        with:
          report-file: Application-Code/backend/dependency-check-report.xml

  #The docker images will build
  docker-build:                 
      - name: build docker image
        run: |
          cd Application-code/backend
          sudo docker build -t ${{ secrets.AWS_ECR_REPO_NAME }} 

  ecr-push:    
    needs: docker-build
    runs-on: ubuntu-latest
    steps: 
      - name: login to aws ecr 
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "Logging into ECR..."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
          docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com 
      - name: Tag and Push Docker Image
        run: |
          IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${{ secrets.AWS_ECR_REPO_NAME }}:${{ github.run_id }}
          docker tag ${{ secrets.AWS_ECR_REPO_NAME }} $IMAGE_URI
          docker push $IMAGE_URI
  
  trivy-scan:
      needs: ecr-push 
      runs-on: ubuntu-latest
      steps:
        - name: Run Trivy Image Scan
          run: trivy image $IMAGE_URI > trivyimage.txt

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest 
    needs: trivy-scan
    steps:
      - name: checkout repository
        uses: action/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: update tag in helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm-chart/backend-application/values.yaml

      - name: commit and push changes
        run: |
          git config user.email "lokeshbabu.nalluri1111@gmil.com"
          git config user.name "nlokeshbabu1"
          git add backend-application/values.yaml
          git commit -m "updated values.yaml file using  ${{ github.run_id }}"
          git push    
          

    
      

